name: build-deploy
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    uses: aiblockofficial/workflows/.github/workflows/build.yml@main
    with:
      REGISTRY: ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
  scan-image:
    uses: aiblockofficial/workflows/.github/workflows/scan-image.yml@main
    secrets: inherit
    needs: build
    with:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }}
  deploy-testnet:
    uses: aiblockofficial/workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    # needs: scan-image
    with:
      REGION: ${{ vars.REGION }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      DEPLOYMENT: testnet-explorer
  deploy-mainnet:
    uses: aiblockofficial/workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    needs: scan-image
    with:
      REGION: ${{ vars.REGION }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      DEPLOYMENT: mainnet-explorer
